### ISSUE TITLE
It didnt work.

### ISSUE THREAD

**Issue by ganjarsetia** [savanihd/user-roles-and-permissions-acl-using-spatie-tutorial-laravel-5.8#3]
After I clone this repo and run:
```
cp .env.example .env
composer install
php artisan key:generate
php artisan migrate 
php artisan db:seed --class=CreateAdminUserSeeder
php artisan db:seed --class=PermissionTableSeeder
```

I cant access the role page & product page.

**Comment by mustafasayilan** [comment]
> After I clone this repo and run:
> 
> ```
> cp .env.example .env
> composer install
> php artisan key:generate
> php artisan migrate 
> php artisan db:seed --class=CreateAdminUserSeeder
> php artisan db:seed --class=PermissionTableSeeder
> ```
> 
> I cant access the role page & product page.

1- change this order 
2- cp .env.example .env
3- composer install
4- php artisan key:generate
5- php artisan migrate 
6- php artisan db:seed --class=PermissionTableSeeder
7- php artisan db:seed --class=CreateAdminUserSeeder
if you create admin user before permission, how can be have a permission admin user ? :)

**Comment by ganjarsetia** [comment]
Nice, it works now. I forgot the order.

btw why dont you move the seeder to `database/seeds/DatabaseSeeder.php` ?
I can make the PR for this.
